services:
  forge-ai-mongodb:
    image: mongo:7.0
    container_name: forge-ai-mongodb
    pull_policy: missing
    ports:
      - "27019:27017"
    environment:
      MONGO_INITDB_DATABASE: forge_ai
    volumes:
      - forge-ai-mongodb-data:/data/db
    labels:
      org.springframework.boot.service-connection: mongodb
    healthcheck:
      test: ["CMD-SHELL", "mongosh --quiet --eval \"db.adminCommand('ping').ok\" localhost:27017/test || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  forge-ai-mongodb-data:
