package com.sitionix.forgeai.infrastructure.githubcli.adapter;

import com.sitionix.forgeai.domain.model.generation.ApiArtifactGenerationRequest;
import com.sitionix.forgeai.domain.model.generation.GeneratedApiArtifact;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import org.springframework.stereotype.Component;

@Component
class ApiGenerationArtifactParser {

    private static final Pattern RUN_URL = Pattern.compile("https://github\\.com/[^\\s)]+/actions/runs/(\\d+)");
    private static final Pattern CODE_BLOCK = Pattern.compile("```(?:[A-Za-z0-9_-]+)?\\R([\\s\\S]*?)```");

    private final ApiGenerationArtifactNaming artifactNaming;

    ApiGenerationArtifactParser(final ApiGenerationArtifactNaming artifactNaming) {
        this.artifactNaming = artifactNaming;
    }

    GeneratedApiArtifact parse(final ApiArtifactGenerationRequest request,
                               final String generationName,
                               final String body) {
        final Matcher matcher = CODE_BLOCK.matcher(body);
        while (matcher.find()) {
            final String snippet = matcher.group(1).trim();
            if (this.artifactNaming.containsExpected(request.expectedArtifact(), snippet)) {
                return new GeneratedApiArtifact(
                        generationName,
                        request.scope(),
                        snippet,
                        this.runId(body),
                        this.runUrl(body),
                        List.of("Generated by GitHub /generate workflow.")
                );
            }
        }
        return null;
    }

    boolean isFailure(final String body) {
        return body != null && (body.contains("Build Job Failed")
                || body.contains("Deploy Job Failed")
                || body.contains("Frontend Contract Publish Failed"));
    }

    String compact(final String body) {
        if (body == null) {
            return "";
        }
        return body.replaceAll("\\s+", " ").trim();
    }

    private Long runId(final String body) {
        final Matcher matcher = RUN_URL.matcher(body);
        return matcher.find() ? Long.parseLong(matcher.group(1)) : null;
    }

    private String runUrl(final String body) {
        final Matcher matcher = RUN_URL.matcher(body);
        return matcher.find() ? matcher.group() : null;
    }
}
