package com.sitionix.forgeai.domain.model.codex;

public enum CodexProgressEventType {
    PROCESS_STARTED,
    PROCESS_STDERR,
    SESSION_STARTED,
    TURN_STARTED,
    TURN_PLAN_UPDATED,
    ITEM_STARTED,
    COMMAND_STARTED,
    COMMAND_OUTPUT,
    COMMAND_COMPLETED,
    FILE_CHANGE,
    AGENT_MESSAGE_DELTA,
    TURN_COMPLETED,
    HEARTBEAT,
    SERVER_REQUEST,
    TURN_INTERRUPT_SENT,
    TURN_INTERRUPTED,
    PROCESS_TERMINATED
}
