environment: localhost
server:
  port: 9099
  servlet:
    context-path: /fgaisox
spring:
  config:
    import: optional:classpath:services.yaml,optional:classpath:agent.yml,optional:classpath:instructions.yaml
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27018/forge_ai}
      uuid-representation: standard
management:
  endpoint:
    health:
      probes:
        enabled: true
      show-details: never
  endpoints:
    web:
      exposure:
        include: "health,info"
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
forge:
  ai:
    launcher:
      default-base-url: http://localhost:9099/fgaisox
      services-config-resource: classpath:services.yaml
forge-ai:
  jobs:
    ready-to-start:
      fixed-delay-ms: 5000
