package com.sitionix.forgeproxyit.infra;
import com.sitionix.forgeai.api.remoteaccess.RemoteAccessProxyDtos;
import com.sitionix.forgeai.infrastructure.agentclient.remoteaccess.RemoteAccessClientDtos;
import com.sitionix.forgeit.domain.endpoint.*;
import com.sitionix.forgeit.domain.endpoint.mockmvc.MockmvcDefault;
import com.sitionix.forgeit.domain.endpoint.wiremock.WiremockDefault;
public final class RemoteAccessEndpoints {
    private RemoteAccessEndpoints() {}
    public static Endpoint<Void,RemoteAccessProxyDtos.Capabilities> capabilitiesApi() { return Endpoint.createContract("/api/v1/infrastructure/agents/remote-access/capabilities",HttpMethod.GET,Void.class,RemoteAccessProxyDtos.Capabilities.class,(MockmvcDefault) context -> context.expectStatus(200).expectResponse("remote-capabilities.json")); }
    public static Endpoint<Void,RemoteAccessClientDtos.Capabilities> capabilitiesUpstream() { return Endpoint.createContract("/api/v1/remote-access/capabilities",HttpMethod.GET,Void.class,RemoteAccessClientDtos.Capabilities.class,(WiremockDefault) context -> context.plainUrl().responseStatus(200).responseBody("remote-capabilities.json")); }
    public static Endpoint<Void,RemoteAccessProxyDtos.Invitation[]> invitationsApi() { return Endpoint.createContract("/api/v1/infrastructure/agents/remote-access/invitations",HttpMethod.GET,Void.class,RemoteAccessProxyDtos.Invitation[].class,(MockmvcDefault) context -> context.expectStatus(200).expectResponse("remote-invitations.json")); }
    public static Endpoint<Void,RemoteAccessClientDtos.Invitation[]> invitationsUpstream() { return Endpoint.createContract("/api/v1/remote-access/invitations",HttpMethod.GET,Void.class,RemoteAccessClientDtos.Invitation[].class,(WiremockDefault) context -> context.plainUrl().responseStatus(200).responseBody("remote-invitations.json")); }
    public static Endpoint<RemoteAccessProxyDtos.InvitationRequest,RemoteAccessProxyDtos.InvitationCreated> inviteApi() { return Endpoint.createContract("/api/v1/infrastructure/agents/remote-access/invitations",HttpMethod.POST,RemoteAccessProxyDtos.InvitationRequest.class,RemoteAccessProxyDtos.InvitationCreated.class,(MockmvcDefault) context -> context.expectStatus(201).expectResponse("remote-created.json").withRequest("remote-invite.json")); }
    public static Endpoint<RemoteAccessClientDtos.InvitationRequest,RemoteAccessClientDtos.InvitationCreated> inviteUpstream() { return Endpoint.createContract("/api/v1/remote-access/invitations",HttpMethod.POST,RemoteAccessClientDtos.InvitationRequest.class,RemoteAccessClientDtos.InvitationCreated.class,(WiremockDefault) context -> context.plainUrl().responseStatus(201).responseBody("remote-created.json").matchesJson("remote-invite.json")); }
    public static Endpoint<Void,Void> cancelApi() { return Endpoint.createContract("/api/v1/infrastructure/agents/remote-access/invitations/22222222-2222-4222-8222-222222222222",HttpMethod.DELETE,Void.class,Void.class,(MockmvcDefault) context -> context.expectStatus(204)); }
    public static Endpoint<Void,Void> cancelUpstream() { return Endpoint.createContract("/api/v1/remote-access/invitations/22222222-2222-4222-8222-222222222222",HttpMethod.DELETE,Void.class,Void.class,(WiremockDefault) context -> context.plainUrl().responseStatus(204)); }
    public static Endpoint<RemoteAccessProxyDtos.ConnectRequest,RemoteAccessProxyDtos.Session> connectApi() { return Endpoint.createContract("/api/v1/infrastructure/agents/remote-access/sessions",HttpMethod.POST,RemoteAccessProxyDtos.ConnectRequest.class,RemoteAccessProxyDtos.Session.class,(MockmvcDefault) context -> context.expectStatus(201).expectResponse("remote-session.json").withRequest("remote-connect.json")); }
    public static Endpoint<RemoteAccessClientDtos.ConnectRequest,RemoteAccessClientDtos.Session> connectUpstream() { return Endpoint.createContract("/api/v1/remote-access/sessions",HttpMethod.POST,RemoteAccessClientDtos.ConnectRequest.class,RemoteAccessClientDtos.Session.class,(WiremockDefault) context -> context.plainUrl().responseStatus(201).responseBody("remote-session.json").matchesJson("remote-connect.json")); }
    public static Endpoint<RemoteAccessProxyDtos.ConnectRequest,RemoteAccessProxyDtos.Session> pendingApi() { return Endpoint.createContract("/api/v1/infrastructure/agents/remote-access/sessions",HttpMethod.POST,RemoteAccessProxyDtos.ConnectRequest.class,RemoteAccessProxyDtos.Session.class,(MockmvcDefault) context -> context.expectStatus(202).expectResponse("remote-provisioning.json").withRequest("remote-connect.json")); }
    public static Endpoint<RemoteAccessClientDtos.ConnectRequest,RemoteAccessClientDtos.Session> pendingUpstream() { return Endpoint.createContract("/api/v1/remote-access/sessions",HttpMethod.POST,RemoteAccessClientDtos.ConnectRequest.class,RemoteAccessClientDtos.Session.class,(WiremockDefault) context -> context.plainUrl().responseStatus(202).responseBody("remote-provisioning.json").matchesJson("remote-connect.json")); }
    public static Endpoint<Void,RemoteAccessProxyDtos.Session[]> sessionsApi() { return Endpoint.createContract("/api/v1/infrastructure/agents/remote-access/sessions",HttpMethod.GET,Void.class,RemoteAccessProxyDtos.Session[].class,(MockmvcDefault) context -> context.expectStatus(200).expectResponse("remote-sessions.json")); }
    public static Endpoint<Void,RemoteAccessClientDtos.Session[]> sessionsUpstream() { return Endpoint.createContract("/api/v1/remote-access/sessions",HttpMethod.GET,Void.class,RemoteAccessClientDtos.Session[].class,(WiremockDefault) context -> context.plainUrl().responseStatus(200).responseBody("remote-sessions.json")); }
    public static Endpoint<Void,RemoteAccessProxyDtos.Session> getApi() { return Endpoint.createContract("/api/v1/infrastructure/agents/remote-access/sessions/11111111-1111-4111-8111-111111111111",HttpMethod.GET,Void.class,RemoteAccessProxyDtos.Session.class,(MockmvcDefault) context -> context.expectStatus(200).expectResponse("remote-session.json")); }
    public static Endpoint<Void,RemoteAccessClientDtos.Session> getUpstream() { return Endpoint.createContract("/api/v1/remote-access/sessions/11111111-1111-4111-8111-111111111111",HttpMethod.GET,Void.class,RemoteAccessClientDtos.Session.class,(WiremockDefault) context -> context.plainUrl().responseStatus(200).responseBody("remote-session.json")); }
    public static Endpoint<Void,RemoteAccessProxyDtos.Session> checkApi() { return Endpoint.createContract("/api/v1/infrastructure/agents/remote-access/sessions/11111111-1111-4111-8111-111111111111/check",HttpMethod.POST,Void.class,RemoteAccessProxyDtos.Session.class,(MockmvcDefault) context -> context.expectStatus(200).expectResponse("remote-session.json")); }
    public static Endpoint<Void,RemoteAccessClientDtos.Session> checkUpstream() { return Endpoint.createContract("/api/v1/remote-access/sessions/11111111-1111-4111-8111-111111111111/check",HttpMethod.POST,Void.class,RemoteAccessClientDtos.Session.class,(WiremockDefault) context -> context.plainUrl().responseStatus(200).responseBody("remote-session.json")); }
    public static Endpoint<Void,RemoteAccessProxyDtos.Session> revokeApi() { return Endpoint.createContract("/api/v1/infrastructure/agents/remote-access/sessions/11111111-1111-4111-8111-111111111111",HttpMethod.DELETE,Void.class,RemoteAccessProxyDtos.Session.class,(MockmvcDefault) context -> context.expectStatus(200).expectResponse("remote-revoked.json")); }
    public static Endpoint<Void,RemoteAccessClientDtos.Session> revokeUpstream() { return Endpoint.createContract("/api/v1/remote-access/sessions/11111111-1111-4111-8111-111111111111",HttpMethod.DELETE,Void.class,RemoteAccessClientDtos.Session.class,(WiremockDefault) context -> context.plainUrl().responseStatus(200).responseBody("remote-revoked.json")); }
    public static Endpoint<Void,RemoteAccessProxyDtos.Session> revokingApi() { return Endpoint.createContract("/api/v1/infrastructure/agents/remote-access/sessions/11111111-1111-4111-8111-111111111111",HttpMethod.DELETE,Void.class,RemoteAccessProxyDtos.Session.class,(MockmvcDefault) context -> context.expectStatus(202).expectResponse("remote-revoking.json")); }
    public static Endpoint<Void,RemoteAccessClientDtos.Session> revokingUpstream() { return Endpoint.createContract("/api/v1/remote-access/sessions/11111111-1111-4111-8111-111111111111",HttpMethod.DELETE,Void.class,RemoteAccessClientDtos.Session.class,(WiremockDefault) context -> context.plainUrl().responseStatus(202).responseBody("remote-revoking.json")); }
}
